apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-deodatus-net-tls
spec:
  secretName: k8s-deodatus-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.deodatus.net
  dnsNames:
    - k8s.deodatus.net
